### ISSUE TITLE
Profile as array for ImageService2

### ISSUE THREAD

**Issue by ra-magnus-welander** [digirati-co-uk/iiif-net#14]
As stated in https://iiif.io/api/image/2.1/#technical-properties, profile for an info.json response should be a list of objects with the first entry being the compliance level. In the current implementation in comes out as a single string, not an array.

Or is there a way to produce an array that I'm not aware of?

I'm not sure which is the best way to implement this, with a custom serializer or a new type for the Profile property on ImageService2.

What do you think?

**Comment by donaldgray** [comment]
Hi @ra-magnus-welander, there is a way to handle this via the `ImageService2.ProfileDescription` property.

The `ImageService2` class has both a `Profile` and `ProfileDescription` property.
* `Profile` is a nullable string where compliance level can be set.
* `ProfileDescription` is a custom type that describes the supported features. This is marked as `[JsonIgnore]` so it is ignored by the default serialiser. Instead a custom serialiser, `ImageService2Serialiser`, handles merging the `Profile` and `ProfileDescription` properties into a single `"profile"` property in the serialised json.

e.g. 
```cs
var imageService = new ImageService2
{
    Id = "https://example",
    Profile = "http://iiif.io/api/image/2/level0.json",
    ProfileDescription = new ProfileDescription
    {
        Formats = new[] { "jpg", "png" }, 
        Qualities = new[] { "color" },
        Supports = new[] { "sizeByWhListed" }
    }
};
```

will output

```json
{
  "@id": "https://example",
  "@type": "ImageService2",
  "profile": [
    "http://iiif.io/api/image/2/level0.json",
    {
      "formats": ["jpg", "png"],
      "qualities": ["color"],
      "supports": ["sizeByWhListed"]
    }
  ]
}

```

See https://github.com/digirati-co-uk/iiif-net/blob/main/src/IIIF/IIIF.Tests/Serialisation/ImageService2SerialiserTests.cs for sample tests.

**Comment by ra-magnus-welander** [comment]
I see, thank you for the thorough explanation!
