### ISSUE TITLE
"Profile" needs to be a complex type

### ISSUE THREAD

**Issue by donaldgray** [digirati-co-uk/iiif-net#4]
Currently `ResourceBase.Profile` is a `string?` but this doesn't satisfy the requirement for accurately rendering an info.json object.

E.g., from IIIF docs:

```json
"profile" : [
    "http://iiif.io/api/image/2/level2.json",
    {
      "formats" : [ "gif", "pdf" ],
      "qualities" : [ "color", "gray" ],
      "maxWidth" : 2000,
      "supports" : [
          "canonicalLinkHeader", "rotationArbitrary", "profileLinkHeader", "http://example.com/feature/"
      ]
    }
  ]
```

Currently we can only output the first string. We need to make this a complex object, with json converter, to handle outputting both string as well [Profile Description](https://iiif.io/api/image/2.1/#profile-description) object.

**Comment by donaldgray** [comment]
Closing - PR #5 adds `ProfileDescription` property to fix. Using `.AsJson()` call will handle combining with `Profile`

**Comment by stephenwf** [comment]
@donaldgray more of a general question on this for libraries. Could a profile identifier be expanded out / queryable when using the library and on the flipside when serialising, could they be safely "compressed". So if I add something like:

```csharp
var imageService = new ImageService2
{
    Id = "https://iiif.io/api/image/2/level2.json",
    ProfileDescription = new ProfileDescription { 
        Formats = new[] { "jpg", "png" },
        Supports = new[] { "sizeByWhListed" }
    },
};
```

The extra description could be discarded as it's already covered in the level2. Or the ID could be "upgraded" to a level.

All hypothetical, but would be really interesting for someone building a fully adaptive image server, picking features based on maybe the content itself, popularity etc.

**Comment by donaldgray** [comment]
@stephenwf yeah I think that should be possible - good idea 👍
